spring.application.name=UserLoginMicroservice-1
spring.config.import=optional\:configserver\:http\://localhost\:7070
server.port=8081
#spring.datasource.url=jdbc:mysql://localhost:3306/Aug15
#spring.datasource.name=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#management.endpoints.web.exposure.exclude="*"